// Generated by CoffeeScript 1.4.0
(function() {
  var w=window, App=w.App, Em=w.Em, oGLOBAL=w.oGLOBAL, oDATA=w.oDATA, oCONTROLS=w.oCONTROLS, MY=w.MY;

  console.log("loading admin1");

  App.adminStart = function() {
    return oDATA.execWhenLoaded(["tblUsers", "tblAccount"], function() {
      App.usersController.set("content", oDATA.GET("tblUsers").emData);
      return App.accountController.set("content", oDATA.GET("tblAccount").emData);
    });
  };

  console.log("loading admin2");

  App.AdminView = App.mainMenuView.extend({
    didInsertElement: function() {
      var frm;
      this._super();
      frm = '#AccountForm';
      return oCONTROLS.UpdatableForm(frm);
    },
    templateName: 'tmpAdminMain',
    viewIx: 5
  });

  App.UsersRowView = Em.View.extend({
    templateName: 'tmpUserRow',
    tagName: ""
  });

  console.log("loading admin3");

  console.log(oDATA.GET("tblAccount").emData);

  App.accountController = Em.ArrayController.create({
    tableName: "tblAccount",
    content: []
  });

  console.log("loading admin4");

  App.usersController = Em.ArrayController.create({
    tableName: "tblUsers",
    content: []
  });

  console.log("loading admin5");

  MY.admin = {};

  //@ sourceURL= /Forms/admin.js;


}).call(this);
