// Generated by CoffeeScript 1.6.2
(function() {
  var w=window, App=w.App, Em=w.Em, oGLOBAL=w.oGLOBAL, oDATA=w.oDATA, oCONTROLS=w.oCONTROLS, MY=w.MY;;  App.docsAccident = function(p) {
    var accidentID, driver, driverID, driverTitle, frmObj, isNew, settings, vehicles;

    frmObj = p.accidentForm.data("ctrl");
    isNew = frmObj.NewRec === 1 ? true : false;
    accidentID = (isNew ? null : frmObj.id);
    driver = $("#lstDrivers");
    driverID = (isNew ? null : driver.data("ctrl").Value);
    driverTitle = "Vairuotojo '" + driver.val() + "' dokumentai";
    vehicles = [];
    if (!isNew) {
      frmObj.vehicles.forEach(function(item) {
        if (!vehicles.findProperty("iD", item.iD)) {
          return vehicles.addObject(item);
        }
      });
    }
    settings = {
      showPhoto: true,
      refreshTree: true,
      categoryOpts: {
        accident: {
          iD: accidentID,
          title: "Įvykio dokumentai"
        },
        driver: {
          iD: driverID,
          title: driverTitle
        },
        vehicles: vehicles
      }
    };
    return oDATA.execWhenLoaded(["tmpUploadForm", "tmpDocsTree"], function() {
      $('#uploadDocsToAccident').UploadFiles(settings);
      return $('#uploadDocsToAccident').next().Tree({
        categoryOpts: settings.categoryOpts
      });
    });
  };

}).call(this);

/*
//@ sourceMappingURL=docsAccident.map
*/
