// Generated by CoffeeScript 1.6.2
(function() {
  var w=window, App=w.App, Em=w.Em, oGLOBAL=w.oGLOBAL, oDATA=w.oDATA, oCONTROLS=w.oCONTROLS, MY=w.MY;  App.TabClaimsRegulationView = Ember.View.extend(App.HidePreviousWindow, {
    previuosWindow: '#divClaimsList',
    thisWindow: '#divClaimRegulation',
    init: function() {
      return this._super();
    },
    templateName: 'tmpClaimRegulation',
    didInsertElement: function() {
      return this._super();
    },
    contentBinding: 'App.claimsRegulationController.content'
  });

  App.claimsRegulationController = Em.ArrayController.create({
    content: [],
    goBack: function() {
      $('#divClaimRegulation').empty().hide().parent().spinner({
        position: 'center',
        img: 'spinnerBig.gif'
      });
      $('#divClaimsList').show();
      return $("body").find("img.spinner").remove();
    }
  });

}).call(this);

/*
//@ sourceMappingURL=tabClaimsRegulation.map
*/
